### ISSUE TITLE
problems with travis-ci: "Too Many Requests'"

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#119] opened 2015-09-07 19:18 UTC
This is annoying - you can not get green test due to connectivity overload:

https://travis-ci.org/scisoft/autocmake/builds/79170217

~~~
self = <test.URLopener instance at 0x18a37a0>
url = '//github.com/docopt/docopt/raw/master/docopt.py'
fp = <socket._fileobject object at 0x17d6350>, errcode = 429
errmsg = 'Too Many Requests'
headers = <httplib.HTTPMessage instance at 0x18a3e18>
    def http_error_default(self, url, fp, errcode, errmsg, headers):
        sys.stderr.write("ERROR: could not fetch %s\n" % url)
>       sys.exit(-1)
E       SystemExit: -1
~~~
Could we please minimize connecting to repositories ? Could we have the github.com/docopt package ready on the spot ?

**Comment by bast** [comment] 2015-09-08 07:29
This issue is duplicate of #117. Closing.

**Closed by bast** 2015-09-08 07:29 UTC
